---
title: "Explore"
author: "William Fisher"
date: "11/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ProjectTemplate)
load.project()
library(knitr)
```

Reading in data
```{r}
Clean_data = read_rds(path = "data/clean_data.Rds")
```

Drop observations that don't have the variables we want
```{r}
Clean_data = Clean_data %>% 
  drop_na()
```

Summary statistics
```{r}
kable(summary(Clean_data))
```

Summary Graph - CPIA
```{r}
ggplot(
  data = Clean_data, 
  mapping = aes(
    x = CPIA_Mean
  )
) +
  geom_histogram(binwidth = 0.2) +
  theme_minimal() +
  labs(title = "Histogram of mean CPIA ratings") +
  xlab("CPIA mean") +
  ylab("Obervations")

ggsave(filename = "graphs/mean_CPIA.png", 
       device = "png", 
       height = 4, 
       width = 8)
```

CPIA over time
```{r}
ggplot(
  data = Clean_data, 
  mapping = aes(
    x = Year, y = CPIA_Mean 
  )
) +
  geom_smooth() +
  geom_jitter(mapping = aes(colour = Country)) +
  theme_minimal() +
  labs(title = "Mean CPIA ratings, over time") +
  xlab("Year") +
  ylab("Mean of CPIA")

ggsave(filename = "graphs/mean_CPIA_over_time.png", 
       device = "png", 
       height = 4, 
       width = 8)
```

Summary Graph - GDP
```{r}
ggplot(
  data = Clean_data, 
  mapping = aes(
    x = Year, y = GDP
  )
) +
  geom_smooth() +
  geom_jitter(mapping = aes(colour = Country)) +
  theme_minimal() +
  labs(title = "GDP pc over time") +
  xlab("Year") +
  ylab("GDP per capita")

ggsave(filename = "graphs/GDP_over_time.png", 
       device = "png", 
       height = 4, 
       width = 8)
```

Summary Graph - GDP
```{r}
ggplot(
  data = Clean_data, 
  mapping = aes(
    x = log(Aid), y = log(GDP)
  )
) +
  geom_jitter(mapping = aes(colour = Country)) +
  geom_smooth() +
  theme_minimal() +
  labs(title = "Aid against GDP") +
  xlab("Aid") +
  ylab("GDP")

ggsave(filename = "graphs/aid_vs_gdp.png", 
       device = "png", 
       height = 4, 
       width = 8)
```

Summary Graph - GDP
```{r}
ggplot(
  data = Clean_data, 
  mapping = aes(
    x = log(Aid), y = log(GDP_growth)
  )
) +
  geom_jitter(mapping = aes(colour = Country)) +
  geom_smooth() +
  theme_minimal() +
  labs(title = "Aid against GDP") +
  xlab("Log Aid") +
  ylab("Log GDP Growth")

ggsave(filename = "graphs/aid_vs_gdp_growth.png",
       plot = last_plot(),
       device = "png", 
       height = 4, 
       width = 8)
```


Saving data
```{r}
Clean_data %>% 
  write_rds("data/clean_data_1.Rds")
```
